/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GradleTwo;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.Test;

public class LibraryTest {
	WebDriver driver;
    @Test public void testSomeLibraryMethod() {
    	System.setProperty("webdriver.chrome.driver", System.getProperty("user.dir")+"/Drivers/chromedriver.exe");
    	driver = new ChromeDriver();
    	driver.manage().window().maximize();
    	driver.get("https://opensource-demo.orangehrmlive.com/");
    }
}
